<?php

namespace Database\Seeders;

use App\Models\WargaModel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nik' => '111111',
                'nama_lengkap' => 'Test-User 1',
                'tanggal_lahir' => '1990-01-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Raya No. 123',
                'roles' => 'rw',
                'pekerjaan' => 'Pegawai',
                'status_perkawinan' => 'Kawin',
                'password' => Hash::make('testuser1'),
                'id_keluarga' => 1,
                'username' => 'adminRW',
            ],
            [
                'nik' => '222222',
                'nama_lengkap' => 'Test-User 2',
                'tanggal_lahir' => '1990-01-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Raya No. 123',
                'roles' => 'rt',
                'pekerjaan' => 'Pegawai',
                'status_perkawinan' => 'Kawin',
                'password' => Hash::make('testuser2'),
                'id_keluarga' => 1,
                'username' => 'adminRT1',
            ],
            [
                'nik' => '333333',
                'nama_lengkap' => 'Alternatif 1',
                'tanggal_lahir' => '1990-01-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Raya No. 123',
                'pekerjaan' => 'Pegawai',
                'roles' => 'warga',
                'status_perkawinan' => 'Kawin',
                'password' => Hash::make('333333'),
                'username' => '333333',
                'id_keluarga' => 1,
            ],
            [
                'nik' => '444444',
                'nama_lengkap' => 'Alternatif 2',
                'tanggal_lahir' => '1991-02-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Melati No. 5',
                'roles' => 'warga',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Belum Kawin',
                'username' => '444444',
                'password' => Hash::make('444444'),
                'id_keluarga' => 2,
            ],
            [
                'nik' => '555555',
                'nama_lengkap' => 'Alternatif 3',
                'tanggal_lahir' => '1989-03-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Merpati No. 10',
                'roles' => 'warga',
                'pekerjaan' => 'Buruh',
                'status_perkawinan' => 'Kawin',
                'username' => '555555',
                'password' => Hash::make('555555'),
                'id_keluarga' => 3,
            ],
            [
                'nik' => '666666',
                'nama_lengkap' => 'Alternatif 4',
                'tanggal_lahir' => '1992-04-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Mawar No. 8',
                'roles' => 'warga',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'Kawin',
                'username' => '666666',
                'password' => Hash::make('666666'),
                'id_keluarga' => 4,
            ],
            [
                'nik' => '777777',
                'nama_lengkap' => 'Alternatif 5',
                'tanggal_lahir' => '1993-05-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Kamboja No. 7',
                'roles' => 'warga',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'username' => '777777',
                'password' => Hash::make('777777'),
                'id_keluarga' => 5,
            ],
            [
                'nik' => '888888',
                'nama_lengkap' => 'Alternatif 6',
                'tanggal_lahir' => '1994-06-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Kenanga No. 6',
                'roles' => 'warga',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'username' => '888888',
                'password' => Hash::make('888888'),
                'id_keluarga' => 6,
            ],
            [
                'nik' => '999999',
                'nama_lengkap' => 'Alternatif 7',
                'tanggal_lahir' => '1988-07-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Anggrek No. 9',
                'roles' => 'warga',
                'pekerjaan' => 'Supir',
                'status_perkawinan' => 'Kawin',
                'username' => '999999',
                'password' => Hash::make('999999'),
                'id_keluarga' => 7,
            ],
            [
                'nik' => '101010',
                'nama_lengkap' => 'Alternatif 8',
                'tanggal_lahir' => '1995-08-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Flamboyan No. 4',
                'roles' => 'warga',
                'pekerjaan' => 'Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'username' => '101010',
                'password' => Hash::make('101010'),
                'id_keluarga' => 8,
            ],
            [
                'nik' => '121212',
                'nama_lengkap' => 'Alternatif 9',
                'tanggal_lahir' => '1996-09-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Cemara No. 3',
                'roles' => 'warga',
                'pekerjaan' => 'Pegawai Negeri',
                'status_perkawinan' => 'Kawin',
                'username' => '121212',
                'password' => Hash::make('121212'),
                'id_keluarga' => 9,
            ],
            [
                'nik' => '131313',
                'nama_lengkap' => 'Alternatif 10',
                'tanggal_lahir' => '1997-10-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Duku No. 2',
                'roles' => 'warga',
                'pekerjaan' => 'Dokter',
                'status_perkawinan' => 'Belum Kawin',
                'username' => '131313',
                'password' => Hash::make('131313'),
                'id_keluarga' => 10,
            ],
            [
                'nik' => '141414',
                'nama_lengkap' => 'Warga Baru 1',
                'tanggal_lahir' => '1990-01-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Kalpataru No. 1',
                'roles' => 'warga',
                'pekerjaan' => 'Pegawai',
                'status_perkawinan' => 'Kawin',
                'username' => '141414',
                'password' => Hash::make('141414'),
                'id_keluarga' => 11,
            ],
            [
                'nik' => '151515',
                'nama_lengkap' => 'Warga Baru 2',
                'tanggal_lahir' => '1991-02-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Kalpataru No. 2',
                'roles' => 'warga',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Belum Kawin',
                'username' => 'wargabaru2',
                'password' => Hash::make('password2'),
                'id_keluarga' => 12,
            ],
            [
                'nik' => '161616',
                'nama_lengkap' => 'Warga Baru 3',
                'tanggal_lahir' => '1992-03-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Kalpataru No. 3',
                'roles' => 'warga',
                'pekerjaan' => 'Buruh',
                'status_perkawinan' => 'Kawin',
                'username' => 'wargabaru3',
                'password' => Hash::make('password3'),
                'id_keluarga' => 13,
            ],
            [
                'nik' => '171717',
                'nama_lengkap' => 'Warga Baru 4',
                'tanggal_lahir' => '1993-04-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Kalpataru No. 4',
                'roles' => 'warga',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'Kawin',
                'username' => 'wargabaru4',
                'password' => Hash::make('password4'),
                'id_keluarga' => 14,
            ],
            [
                'nik' => '181818',
                'nama_lengkap' => 'Warga Baru 5',
                'tanggal_lahir' => '1994-05-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Kalpataru No. 5',
                'roles' => 'warga',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'username' => 'wargabaru5',
                'password' => Hash::make('password5'),
                'id_keluarga' => 15,
            ],
            [
                'nik' => '191919',
                'nama_lengkap' => 'Warga Baru 6',
                'tanggal_lahir' => '1995-06-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Kalpataru No. 6',
                'roles' => 'warga',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'username' => 'wargabaru6',
                'password' => Hash::make('password6'),
                'id_keluarga' => 16,
            ],
            [
                'nik' => '202020',
                'nama_lengkap' => 'Warga Baru 7',
                'tanggal_lahir' => '1996-07-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Kalpataru No. 7',
                'roles' => 'warga',
                'pekerjaan' => 'Supir',
                'status_perkawinan' => 'Kawin',
                'username' => 'wargabaru7',
                'password' => Hash::make('password7'),
                'id_keluarga' => 17,
            ],
            [
                'nik' => '212121',
                'nama_lengkap' => 'Warga Baru 8',
                'tanggal_lahir' => '1997-08-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Kalpataru No. 8',
                'roles' => 'warga',
                'pekerjaan' => 'Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'username' => 'wargabaru8',
                'password' => Hash::make('password8'),
                'id_keluarga' => 18,
            ],
            [
                'nik' => '222222',
                'nama_lengkap' => 'Warga Baru 9',
                'tanggal_lahir' => '1998-09-01',
                'jenis_kelamin' => 'Laki-Laki',
                'alamat_domisili' => 'Jl. Kalpataru No. 9',
                'roles' => 'warga',
                'pekerjaan' => 'Pegawai Negeri',
                'status_perkawinan' => 'Kawin',
                'username' => 'wargabaru9',
                'password' => Hash::make('password9'),
                'id_keluarga' => 19,
            ],
            [
                'nik' => '232323',
                'nama_lengkap' => 'Warga Baru 10',
                'tanggal_lahir' => '1999-10-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_domisili' => 'Jl. Kalpataru No. 10',
                'roles' => 'warga',
                'pekerjaan' => 'Dokter',
                'status_perkawinan' => 'Belum Kawin',
                'username' => 'wargabaru10',
                'password' => Hash::make('password10'),
                'id_keluarga' => 20,
            ],
            
        ];

        foreach ($data as $item) {
            DB::table('warga')->updateOrInsert(
                ['nik' => $item['nik']], // Unique condition
                $item // Data to insert or update
            );
        }
    }
}